###
curl -H "x-admin-key:{{ADMIN_API_KEY}}" "https://tribelife.app/api/admin/users/lookup?handle=mary71"


###
curl -X POST "https://tribelife.app/api/admin/users/ban" \
    -H "x-admin-key: {{ADMIN_API_KEY}}" -H "Content-Type: application/json" \
    -d '{"userId": 1210, "reason": "spam / bot", "announce":true}'